security:

    encoders:

        Multiservices\ArxisBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SYSTEM:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_SYSTEM,ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        user_db:
            entity: {class: Multiservices\ArxisBundle\Entity\Usuario, property: username}
    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _arxis_login
                default_target_path: _login_ok
                always_use_default_target_path: true 
            logout:
                path:   _logout_ok
                target: _arxis_login

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/arxis/user, roles: ROLE_ADMIN }
        - { path: ^/arxis/role, roles: ROLE_ADMIN }

        
        