security:

    encoders:

        FOS\UserBundle\Model\UserInterface: 
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SYSTEM:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_SYSTEM,ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody
        login:
            pattern:  ^/(login$|register)
            anonymous: true
        resetting:
            pattern:  ^/resetting/(request|send-email|check-email|reset|reset/$)
            anonymous: true    

        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                 path:   fos_user_security_logout
                 target: fos_user_security_login
            anonymous:   false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/arxis/user, roles: ROLE_ADMIN }
        - { path: ^/arxis/role, roles: ROLE_ADMIN }

        
        